name = "DataVisualization"
uuid = "de49ba16-8f50-42c0-953a-2dd264fb1ae7"
authors = ["Pietro Vertechi <pietro.vertechi@veos.digital> and contributors"]
version = "0.1.0"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
LayeredLayouts = "f4a74d36-062a-4d48-97cd-1356bad1de4e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
AlgebraOfGraphics = "0.4, 0.5, 0.6"
CSV = "0.9"
Clustering = "0.14"
Distances = "0.10"
GLM = "1"
GraphMakie = "0.3"
Graphs = "1.4"
JSServe = "1"
LayeredLayouts = "0.2"
Makie = "0.14, 0.15"
Missings = "1"
MultivariateStats = "0.8"
Observables = "0.4"
OrderedCollections = "1"
RelocatableFolders = "0.1"
StatsBase = "0.33"
StatsModels = "0.6"
StructArrays = "0.6"
Tables = "1"
WGLMakie = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
